# Generated by Django 3.1.7 on 2021-05-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('created_Date', models.DateField(auto_now_add=True)),
                ('modified_Date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_Name', models.CharField(max_length=100)),
                ('plan_Type', models.CharField(choices=[('Layout', 'Layout')], max_length=10)),
                ('plan_Number', models.IntegerField()),
                ('plan_Location', models.CharField(max_length=100)),
                ('plan_City', models.CharField(max_length=100)),
                ('plan_Area_In_Acres', models.IntegerField()),
                ('plan_date', models.DateTimeField(auto_now_add=True)),
                ('plan_image', models.ImageField(upload_to='planImages')),
                ('plan_description', models.CharField(max_length=500)),
                ('no_of_plots', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('created_Date', models.DateField(auto_now_add=True)),
                ('modified_Date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property_type_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('created_Date', models.DateField(auto_now_add=True)),
                ('modified_Date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property_Number', models.IntegerField(default=0)),
                ('total_Area_Of_Property', models.IntegerField()),
                ('property_width', models.PositiveIntegerField()),
                ('property_height', models.PositiveIntegerField()),
                ('property_availability', models.CharField(choices=[('Available', 'Available'), ('Hold', 'Hold'), ('Sold', 'Sold')], max_length=10)),
                ('rate_Of_Plot', models.IntegerField()),
                ('stamp_Duty', models.BooleanField(default=False)),
                ('registry', models.BooleanField(default=False)),
                ('RL', models.BooleanField(default=False)),
                ('FSI', models.BooleanField(default=False)),
                ('NA', models.BooleanField(default=False)),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Property_PlanId', to='property.plan')),
                ('property_Type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_propertyType', to='property.propertytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('created_Date', models.DateField(auto_now_add=True)),
                ('modified_Date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amenity_name', models.CharField(max_length=100)),
                ('amenity_description', models.CharField(max_length=500)),
                ('amenity_image', models.ImageField(upload_to='amenityImages')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
